const numbers = {
    "ek": 1,
    "do": 2,
    "teen": 3,
    "char": 4,
    "paanch": 5,
    "chhe": 6,
    "saat": 7,
    "aath": 8,
    "nau": 9,
    "das": 10,

    "gyarah": 11,
    "baarah": 12,
    "terah": 13,
    "chaudah": 14,
    "pandrah": 15,
    "solah": 16,
    "satrah": 17,
    "athaarah": 18,
    "unnees": 19,
    "bees": 20,

    "ikkees": 21,
    "baais": 22,
    "teis": 23,
    "chaubees": 24,
    "pachchees": 25,
    "chhabbees": 26,
    "sattaais": 27,
    "athaaais": 28,
    "untees": 29,
    "tees": 30,

    "iktees": 31,
    "battees": 32,
    "taintees": 33,
    "chauntees": 34,
    "paintees": 35,
    "chhattees": 36,
    "saintees": 37,
    "adtees": 38,
    "untaalees": 39,
    "chaalees": 40,

    "iktaalees": 41,
    "bayaalees": 42,
    "tentaalees": 43,
    "chaawaalees": 44,
    "paitaalees": 45,
    "chhiyaalees": 46,
    "sentaalees": 47,
    "adtaalees": 48,
    "unchaas": 49,
    "chaas": 50,

    "ikyaavan": 51,
    "baavan": 52,
    "tirpan": 53,
    "chauvan": 54,
    "pachpan": 55,
    "chhappan": 56,
    "sattaavan": 57,
    "athaavan": 58,
    "unsath": 59,
    "saath": 60,

    "iksath": 61,
    "baasath": 62,
    "tirsath": 63,
    "chaunsath": 64,
    "painsath": 65,
    "chhiyaasath": 66,
    "sadsath": 67,
    "adsath": 68,
    "unhattar": 69,
    "sattar": 70,

    "ikhattar": 71,
    "bahattar": 72,
    "tihattar": 73,
    "chauhattar": 74,
    "pachhattar": 75,
    "chhihattar": 76,
    "satahattar": 77,
    "athahattar": 78,
    "uniyaasi": 79,
    "assi": 80,

    "ikyaasi": 81,
    "bayaasi": 82,
    "tiraasi": 83,
    "chauraasi": 84,
    "pachaasi": 85,
    "chhiyaasi": 86,
    "sataasi": 87,
    "athaasi": 88,
    "navaasi": 89,
    "nabbe": 90,

    "ikyaanave": 91,
    "baanave": 92,
    "tiraanave": 93,
    "chauraanave": 94,
    "pachaanave": 95,
    "chhiyaanave": 96,
    "sattaanave": 97,
    "athaanave": 98,
    "ninyaanave": 99,
    "sau": 100
};

module.exports = numbers;