const numbers_BEN = {
    "ek": 1,
    "dui": 2,
    "tin": 3,
    "char": 4,
    "pach": 5,
    "chhoy": 6,
    "sat": 7,
    "at": 8,
    "noy": 9,
    "dos": 10,

    "egaro": 11,
    "baro": 12,
    "tero": 13,
    "chouddo": 14,
    "ponero": 15,
    "sholo": 16,
    "shotero": 17,
    "atharo": 18,
    "unish": 19,
    "bish": 20,

    "ekush": 21,
    "baish": 22,
    "teish": 23,
    "chobbish": 24,
    "pochish": 25,
    "chhabbish": 26,
    "satash": 27,
    "athash": 28,
    "untrish": 29,
    "trish": 30,

    "ektrish": 31,
    "bottrish": 32,
    "tetrish": 33,
    "chauttrish": 34,
    "poytrish": 35,
    "chhattrish": 36,
    "saitrish": 37,
    "atotrish": 38,
    "unochollish": 39,
    "chollish": 40,

    "ekchollish": 41,
    "biyallish": 42,
    "tetallish": 43,
    "chouallish": 44,
    "poytallish": 45,
    "chhechollish": 46,
    "satchollish": 47,
    "atchollish": 48,
    "unoponchash": 49,
    "ponchash": 50,

    "ekanno": 51,
    "bahanno": 52,
    "tiranno": 53,
    "chauanno": 54,
    "pachanno": 55,
    "chhappanno": 56,
    "satanno": 57,
    "atanno": 58,
    "unoshat": 59,
    "shat": 60,

    "ekshotti": 61,
    "bashotti": 62,
    "treshotti": 63,
    "chausotti": 64,
    "poyshotti": 65,
    "chheshotti": 66,
    "satsotti": 67,
    "atshotti": 68,
    "unoshottor": 69,
    "shottor": 70,

    "ekattor": 71,
    "bahattor": 72,
    "tihattor": 73,
    "chouattor": 74,
    "pochattor": 75,
    "chhiyattor": 76,
    "satattor": 77,
    "atattor": 78,
    "unashi": 79,
    "ashi": 80,

    "ekashi": 81,
    "birashi": 82,
    "tirashi": 83,
    "churashi": 84,
    "pachashi": 85,
    "chhiyashi": 86,
    "sattashi": 87,
    "atashi": 88,
    "unonobboi": 89,
    "nobboi": 90,

    "ekanobboi": 91,
    "birannobboi": 92,
    "tiranobboi": 93,
    "churanobboi": 94,
    "panchanobboi": 95,
    "chhiyanobboi": 96,
    "satanobboi": 97,
    "atanobboi": 98,
    "niranobboi": 99,
    "eksho": 100
};
module.exports = numbers_BEN;